export const cartsState={
    carts:{
        data:[],
        limit:9,
        offset:0,
    },
    favourites:[],
    searchState:{
        'title':true,
        'genres':false,
    },
    currentSearchState:'title',
    currentSortState:'vote_average',
    sortState:{
        'release_date':false,
        'vote_average':true,
    },
    sortOrder:'desc',
    searchValue:'',
};